language: android
jdk:
  - oraclejdk8
before_script:
  - mv scripts/travis/secrets-travis.xml app/src/main/res/values
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27

    # Additional components
    - extra-google-google_play_services
    - addon-google_apis-google-27

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-27