language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - addon-google_apis-google-27

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-27